name: prometheus-conversation-agent
region: nyc
services:
  - name: api
    github:
      repo: KIKW12/Prometheus
      branch: main
      deploy_on_push: true
    source_dir: /
    environment_slug: python
    http_port: 8080
    instance_size_slug: apps-s-1vcpu-1gb
    instance_count: 1
    run_command: gunicorn --bind 0.0.0.0:8080 server:app
    envs:
      - key: GOOGLE_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: SUPABASE_URL
        scope: RUN_TIME
        type: SECRET
      - key: SUPABASE_SERVICE_KEY
        scope: RUN_TIME
        type: SECRET
